### PR TITLE
C: Properly implement defined rules using the empty list.

### PR DESCRIPTION
**Pull request by shlevy**
Part of #363.

### CODE REVIEW

**Comment by andreasabel** [comment]
Thanks.
My suggestion would be to generalize `Exp` in `CF.hs` to
```haskell
type Exp = Exp' String
data Exp' f
  = App f [Exp]       -- ^ (Possibly defined) label applied to expressions.
  | Var String        -- ^ Function parameter.
  | LitInt Integer
  | LitDouble Double
  | LitChar Char
  | LitString String
  deriving (Eq, Functor)
```
Then replace, in the C backend, `[]` by `Null` and `(:)` by the respective `make_ListXXX`.  (Btw. there is `isNilFun` and `isConsFun` to check for these special labels.)
This is likely still not enough, we need to have the list type `XXX`.  This could be saved in the `TypeChecker.hs`, producing a `Exp' (String,Cat)` remembering the target type of the `App f es`.  Spinning this further, the `Cat` is only needed for list constructors, so maybe `Exp' Label` would be sufficient where
```haskell
data Label
  = OrdinaryLabel String
  | NilLabel  Cat    -- ^ []
  | ConsLabel Cat   -- ^ (:)
  | OneLabel  Cat    -- ^ (:[])
```

**Comment by shlevy** [comment]
Makes sense, will try to carve out some time!

**Comment by andreasabel** [comment]
I fixed this problem in a way similar as I wrote in the comment.
Mainly, we remember the typing information from the type checker, so we
- do not need to run the type checker again (was so in the OO backends) when translating the definitions
- can use the typing information to select the right list constructors.

**Comment by shlevy** [comment]
Awesome! Sorry this sat for so long, I only have a little time here and there to work on the project using BNFC at the moment. Hopefully will be able to pick up the rust backend soon!

**Comment by andreasabel** [comment]
Yeah, looking forward to the Rust backend!  

If you find any more bugs, do not hesitate to report them!  (Trying to understand how things work is the best way to discover bugs...)

**Pull request closed without merging**
