### PR TITLE
Integration of incremental lexer with incremental parser. 

### PR DESCRIPTION
**Pull request by jyp**
Documented in tobias' thesis

### CODE REVIEW

**Comment by andreasabel** [comment]
Here is the thesis: https://gupea.ub.gu.se/handle/2077/36982

@jyp @tobsan This looks like a larger pull request with substantially new features.  It would be nice to have this in BNFC, if it is sufficiently tested and documented.  Anyone of you interested in merging it and maintaining it for a couple of years, say 5?

**Comment by jyp** [comment]
I can't take care of the merge, but I'll be happy to give background info
on request.

Cheers,
JP.

**Comment by tobsan** [comment]
Fun to see that this is still interesting to get into BNFC. 

I can take care of the merge (probably, if I really try) but since I'm no longer doing anything related with BNFC, it's probably better that @jyp takes care of the background info.

**Comment by tobsan** [comment]
There are no tests afaik, apart from some test grammars and source files used to sanity check during development.

While it would be fun to maintain a backend for BNFC, I'm not sure I would be able to do much more than simple bug fixes. As discussed in the thesis, there are (at least) two main issues currently: a bug of unknown origin, and the lack of error reporting from the parser and a strategy for that.

As for documentation, there are the papers by @jyp and Koen and my thesis, but it would probably need some effort to make it user-friendly.

**Comment by andreasabel** [comment]
Happy new year!  And, any new year resolutions to take care of this abandoned child?
We are sorry, the orphanage is full, so we closed the baby flap.

**Comment by tobsan** [comment]
@andreasabel Not from me, unfortunately. The threshold is just too high for me to fix the remaining issues before being able to take maintainership of the code :/. I suppose that means this PR can be closed unless someone else is eager to do the work.

**Comment by andreasabel** [comment]
@tobsan Thanks for the reply.  This is unfortunate, but I can understand that you have moved on to other things.

I am closing this PR now, maybe someone wants to resurrect it in the future...

**Pull request closed without merging**
